AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'lift-log-sam

  Sample SAM Template for lift-log-sam

  '
Globals:
  Function:
    Timeout: 5
Resources:
  LiftLogAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: '''GET,OPTIONS,POST,PUT,PATCH'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
        AllowOrigin: '''*'''
  AddWorkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lift-log/d9a3f4edf0e85354e010520d050d958e
      Handler: app.handler
      Runtime: python3.7
      Role: arn:aws:iam::415227642804:role/lambda-vpc-role
      Layers:
      - Ref: LiftLogLayer
      Events:
        AddWorkout:
          Type: Api
          Properties:
            Path: /workout
            Method: POST
            RestApiId:
              Ref: LiftLogAPI
  GetWorkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lift-log/3e3c5264e25ecfcee7267993079207c6
      Handler: app.handler
      Runtime: python3.7
      Role: arn:aws:iam::415227642804:role/lambda-vpc-role
      Layers:
      - Ref: LiftLogLayer
      Events:
        GetWorkout:
          Type: Api
          Properties:
            Path: /workout/{date}
            Method: GET
            RestApiId:
              Ref: LiftLogAPI
  QueryWorkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lift-log/e3364ed4ecc4a6966ba0e2679f3d3709
      Handler: app.handler
      Runtime: python3.7
      Role: arn:aws:iam::415227642804:role/lambda-vpc-role
      Layers:
      - Ref: LiftLogLayer
      Events:
        GetWorkout:
          Type: Api
          Properties:
            Path: /workout/query
            Method: POST
            RestApiId:
              Ref: LiftLogAPI
  CreateExerciseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lift-log/6d5cfbfa7822838de7c35731d90d6f34
      Handler: app.handler
      Runtime: python3.7
      Role: arn:aws:iam::415227642804:role/lambda-vpc-role
      Layers:
      - Ref: LiftLogLayer
      Events:
        CreateExercise:
          Type: Api
          Properties:
            Path: /exercise
            Method: POST
            RestApiId:
              Ref: LiftLogAPI
  LiftLogLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: LiftLogLayer
      Description: layer with LiftLog helpers
      ContentUri: s3://lift-log/adbd41397977a26defc963705cfec1cd
      CompatibleRuntimes:
      - python3.7
      - python3.6
      LicenseInfo: MIT
      RetentionPolicy: Retain
