AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lift-log-sam

  Sample SAM Template for lift-log-sam

Parameters:
  LiftLogDbPw:
    Type: String
  LiftLogDbUser:
    Type: String

Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        LIFTLOG_DB_PW: !Ref LiftLogDbPw
        LIFTLOG_DB_USER: !Ref LiftLogDbUser

Resources:
  LiftLogAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,OPTIONS,POST,PUT,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

        
  AddWorkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/workout/POST
      Handler: app.handler
      Runtime: python3.7
      Role: arn:aws:iam::415227642804:role/lambda-vpc-role
      Layers:
        - !Ref LiftLogLayer
      Events:
        AddWorkout:
          Type: Api 
          Properties:
            Path: /workout
            Method: POST
            RestApiId: !Ref LiftLogAPI


  QueryWorkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/workout/query
      Handler: app.handler
      Runtime: python3.7
      Role: arn:aws:iam::415227642804:role/lambda-vpc-role
      Layers:
        - !Ref LiftLogLayer
      Events:
        QueryWorkout:
          Type: Api 
          Properties:
            Path: /workout/query
            Method: POST
            RestApiId: !Ref LiftLogAPI


  AddSetToWorkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/workout/set/POST
      Handler: app.handler
      Runtime: python3.7
      Role: arn:aws:iam::415227642804:role/lambda-vpc-role
      Layers:
        - !Ref LiftLogLayer
      Events:
        AddSetToWorkout:
          Type: Api 
          Properties:
            Path: /workout/{workout_id}/set
            Method: POST
            RestApiId: !Ref LiftLogAPI


  UpdateSetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/workout/set/POST
      Handler: app.handler
      Runtime: python3.7
      Role: arn:aws:iam::415227642804:role/lambda-vpc-role
      Layers:
        - !Ref LiftLogLayer
      Events:
        UpdateSet:
          Type: Api 
          Properties:
            Path: /workout/{workout_id}/set/{set_id}
            Method: PUT
            RestApiId: !Ref LiftLogAPI
    

  CreateExerciseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/exercise/POST
      Handler: app.handler
      Runtime: python3.7
      Role: arn:aws:iam::415227642804:role/lambda-vpc-role
      Layers:
        - !Ref LiftLogLayer
      Events:
        CreateExercise:
          Type: Api 
          Properties:
            Path: /exercise
            Method: POST
            RestApiId: !Ref LiftLogAPI


  LiftLogLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: LiftLogLayer
      Description: layer with LiftLog helpers
      ContentUri: layer/
      # ContentUri: .aws-sam/build/LiftLogLayerDummy
      CompatibleRuntimes:
        - python3.7
        - python3.6
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
